ULKELER = [
    {"ad": "Türkiye", "kod": "TR", "num": "792"},
    {"ad": "Almanya", "kod": "DE", "num": "276"},
    {"ad": "Amerika Birleşik Devletleri", "kod": "US", "num": "840"},
    {"ad": "Avustralya", "kod": "AU", "num": "036"},
    {"ad": "Avusturya", "kod": "AT", "num": "040"},
    {"ad": "Belçika", "kod": "BE", "num": "056"},
    {"ad": "Birleşik Arap Emirlikleri", "kod": "AE", "num": "784"},
    {"ad": "Birleşik Krallık", "kod": "GB", "num": "826"},
    {"ad": "Brezilya", "kod": "BR", "num": "076"},
    {"ad": "Bulgaristan", "kod": "BG", "num": "100"},
    {"ad": "Çek Cumhuriyeti", "kod": "CZ", "num": "203"},
    {"ad": "Çin", "kod": "CN", "num": "156"},
    {"ad": "Danimarka", "kod": "DK", "num": "208"},
    {"ad": "Endonezya", "kod": "ID", "num": "360"},
    {"ad": "Estonya", "kod": "EE", "num": "233"},
    {"ad": "Fas", "kod": "MA", "num": "504"},
    {"ad": "Finlandiya", "kod": "FI", "num": "246"},
    {"ad": "Fransa", "kod": "FR", "num": "250"},
    {"ad": "Güney Kore", "kod": "KR", "num": "410"},
    {"ad": "Hindistan", "kod": "IN", "num": "356"},
    {"ad": "Hollanda", "kod": "NL", "num": "528"},
    {"ad": "İngiltere", "kod": "GB", "num": "826"},
    {"ad": "İrlanda", "kod": "IE", "num": "372"},
    {"ad": "İspanya", "kod": "ES", "num": "724"},
    {"ad": "İsveç", "kod": "SE", "num": "752"},
    {"ad": "İsviçre", "kod": "CH", "num": "756"},
    {"ad": "İtalya", "kod": "IT", "num": "380"},
    {"ad": "Japonya", "kod": "JP", "num": "392"},
    {"ad": "Kanada", "kod": "CA", "num": "124"},
    {"ad": "Kolombiya", "kod": "CO", "num": "170"},
    {"ad": "Letonya", "kod": "LV", "num": "428"},
    {"ad": "Litvanya", "kod": "LT", "num": "440"},
    {"ad": "Lüksemburg", "kod": "LU", "num": "442"},
    {"ad": "Macaristan", "kod": "HU", "num": "348"},
    {"ad": "Makedonya", "kod": "MK", "num": "807"},
    {"ad": "Meksika", "kod": "MX", "num": "484"},
    {"ad": "Mısır", "kod": "EG", "num": "818"},
    {"ad": "Norveç", "kod": "NO", "num": "578"},
    {"ad": "Pakistan", "kod": "PK", "num": "586"},
    {"ad": "Polonya", "kod": "PL", "num": "616"},
    {"ad": "Portekiz", "kod": "PT", "num": "620"},
    {"ad": "Romanya", "kod": "RO", "num": "642"},
    {"ad": "Rusya", "kod": "RU", "num": "643"},
    {"ad": "Suudi Arabistan", "kod": "SA", "num": "682"},
    {"ad": "Sırbistan", "kod": "RS", "num": "688"},
    {"ad": "Slovakya", "kod": "SK", "num": "703"},
    {"ad": "Slovenya", "kod": "SI", "num": "705"},
    {"ad": "Şili", "kod": "CL", "num": "152"},
    {"ad": "Tayland", "kod": "TH", "num": "764"},
    {"ad": "Tunus", "kod": "TN", "num": "788"},
    {"ad": "Ukrayna", "kod": "UA", "num": "804"},
    {"ad": "Yunanistan", "kod": "GR", "num": "300"},
    {"ad": "Yeni Zelanda", "kod": "NZ", "num": "554"},
]
